/* A packrat parser generated by PackCC 1.8.0 */

#ifndef PCC_INCLUDED_PARSER_H
#define PCC_INCLUDED_PARSER_H

#include "string_t.h"
#include "emmem.h"
#include "em_result.h"
#include "ast.h"
typedef struct parser_reader_t {
  string_t * line;
  int cur;
} parser_reader_t;

em_result
parser_reader_new(parser_reader_t * out, string_t * str);

int
parser_reader_getchar(parser_reader_t * reader);
#ifdef __cplusplus
extern "C" {
#endif

typedef struct parser_context_tag parser_context_t;

parser_context_t *parser_create(void *auxil);
int parser_parse(parser_context_t *ctx, void **ret);
void parser_destroy(parser_context_t *ctx);

#ifdef __cplusplus
}
#endif

#endif /* !PCC_INCLUDED_PARSER_H */
